import { writeFile, chmod } from 'node:fs/promises'
import { join } from 'node:path'
import { randomBytes } from 'node:crypto'
import { existsSync } from 'node:fs'

export interface WritingDeskConfig {
  appId: number
  privateKeyBase64: string
  installationId: number
  clientId: string
  clientSecret: string
  owner: string
  repo: string
  contentPath: string
  defaultBranch: string
  origin: string
}

function generateJwtSecret(): string {
  return randomBytes(32).toString('hex')
}

export function buildEnvContent(config: WritingDeskConfig): string {
  const jwtSecret = generateJwtSecret()
  return [
    `# Generated by writingdesk-setup on ${new Date().toISOString().split('T')[0]}`,
    '',
    '# GitHub App — repository operations',
    `GITHUB_APP_ID=${config.appId}`,
    `GITHUB_APP_PRIVATE_KEY_BASE64=${config.privateKeyBase64}`,
    `GITHUB_INSTALLATION_ID=${config.installationId}`,
    '',
    '# GitHub OAuth — user sign-in',
    `GITHUB_OAUTH_CLIENT_ID=${config.clientId}`,
    `GITHUB_OAUTH_CLIENT_SECRET=${config.clientSecret}`,
    '',
    '# Target repository',
    `GITHUB_OWNER=${config.owner}`,
    `GITHUB_REPO=${config.repo}`,
    `GITHUB_CONTENT_PATH=${config.contentPath}`,
    `GITHUB_DEFAULT_BRANCH=${config.defaultBranch}`,
    '',
    '# Session signing key',
    `JWT_SECRET=${jwtSecret}`,
    '',
    '# Server',
    'PORT=3000',
    `ORIGIN=${config.origin}`,
    '',
  ].join('\n')
}

export function buildComposeContent(): string {
  return [
    '# Generated by writingdesk-setup — for local integration testing only',
    '# Usage: docker compose -f docker-compose.local.yml up --build',
    'services:',
    '  writingdesk:',
    '    build:',
    '      context: .',
    '      dockerfile: packages/app/Dockerfile',
    '    ports:',
    '      - "127.0.0.1:3000:3000"',
    '    env_file:',
    '      - .env',
    '    environment:',
    '      ORIGIN: "http://localhost:3000"',
    '    volumes:',
    '      - writingdesk_repo:/var/writingdesk/repo',
    '      - writingdesk_builds:/var/writingdesk/astro-build',
    '    healthcheck:',
    '      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]',
    '      interval: 10s',
    '      timeout: 5s',
    '      retries: 3',
    '',
    'volumes:',
    '  writingdesk_repo:',
    '  writingdesk_builds:',
    '',
  ].join('\n')
}

export async function writeOutputFiles(config: WritingDeskConfig, outDir: string): Promise<void> {
  const envPath = join(outDir, '.env')
  const composePath = join(outDir, 'docker-compose.local.yml')

  await writeFile(envPath, buildEnvContent(config), 'utf-8')
  await chmod(envPath, 0o600)  // owner read/write only
  await writeFile(composePath, buildComposeContent(), 'utf-8')

  // Warn if .gitignore doesn't cover .env
  const gitignorePath = join(outDir, '.gitignore')
  if (existsSync(gitignorePath)) {
    const { readFile } = await import('node:fs/promises')
    const gitignore = await readFile(gitignorePath, 'utf-8')
    if (!gitignore.includes('.env')) {
      console.warn('\nWarning: .env is not in your .gitignore. Add it to avoid committing secrets.\n')
    }
  }
}
